# Generated by Django 6.1.1 on 2026-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_characteristics_characteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='footballclub',
            name='characteristic',
        ),
        migrations.RemoveField(
            model_name='footballclub',
            name='country',
        ),
        migrations.RemoveField(
            model_name='footballclub',
            name='league',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='FootballClub',
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
